### PR TITLE
Fix specs

### PR DESCRIPTION
**Pull request by esposito**
In this pull request I introduce the guard-compat gem to fix some of the specs. I could reproduce the last two failing specs, but they were hard to fix without breaking some of the other specs, so I left them there for now (something to do with gems in the gemfile).

In addition I add a spec for my run_all fix submitted in https://github.com/modeset/guard-teaspoon/pull/39.

### CODE REVIEW

**Comment by jejacks0n** [comment]
!! Thanks!

**Comment by esposito** [comment]
The root cause of the run_all function not running all test files seems the be the fact that the options hash is shared between the runner and the Teaspoon console. This could be fixed by cloning the options hash before passing it on to this console. I was not sure whether this fix, though nicer, would break some other functionality, so I left it out.

**Comment by jejacks0n** [comment]
You want to give it a shot? I've got some time slated to work on this shortly, and so I'm pretty willing to merge any PR and see where it nets out.

**Comment by e2** [comment]
Hi guys!

I've migrated/sent PRs for many popular Guard plugins to use Guard::Compat. (guard-teaspoon wasn't popular/active enough to fit in the top 25).

If you have any issues, let me know (mention me, etc.).

I'd recommend checking out changes I made to `guard-haml` and `guard-brakeman` (check the revision history) - which also included migrating to RSpec 3.2, some reorganizing, etc.

**Pull request merged**
